name: spec2vec-dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python
  - gensim >=4.3.3
  - matchms >=0.27.0
  - numba
  - numpy
  - pip
  - scipy
  - tqdm
  - bump2version
  - isort>=5.1.0
  - pylint<2.12.0
  - prospector
  - pytest
  - pytest-cov
  - sphinx>=4.0.0
  - sphinx_rtd_theme
  - sphinxcontrib-apidoc
  - yapf

