{% set name = "spec2vec" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

extra:
  channels:
    - nlesc
    - conda-forge
    - bioconda

build:
  noarch: python
  preserve_egg_dir: True
  number: 0
  skip: True # [py2k]
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv

requirements:
  build:
    - conda-build
    - conda-verify
    - pytest-runner
    - python
    - matchms >=0.6.2
    - numpy {{ numpy }}
    - setuptools
  host:
    - python >=3.7
    - pip
    - pytest-runner
    - setuptools
  run:
    - gensim >=4.2.0
    - matchms >=0.14.0, <=0.26.4
    - numba >=0.51
    - numpy
    - pip
    - python >=3.7
    - scipy <=1.10.1
    - tqdm

test:
  imports:
    - spec2vec

about:
  home: https://github.com/iomega/spec2vec
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Word2Vec based similarity measure of mass spectrometry data.
  description: Word2Vec based similarity measure of mass spectrometry data.
  doc_url: https://spec2vec.readthedocs.io/
  dev_url: https://github.com/iomega/spec2vec

extra:
  recipe-maintainers:
    - fdiblen
    - florian-huber
